portafolio:
  capital_inicial: 10000.0
  apalancamiento: 1.0
  comision: 0.001
  slippage: 0.001

Entorno:
  window_size: 30
  max_drawdown_permitido: 0.2
  factor_aversion_riesgo: 2
  umbral_mantener_posicion: 0.05

SAC:
