# ===================================================================
# CONFIGURACIÓN CENTRALIZADA - SISTEMA DE TRADING AUTOMATIZADO
# ===================================================================

# --- ADQUISICIÓN DE DATOS ---
data_downloader:
  limit: 1500                    # Límite por llamada API

# --- PREPROCESAMIENTO ---
preprocesamiento:
  interpol_method: 'linear'      # Método de interpolación para manejar NaN
  indicadores:
    SMA_short: 50
    SMA_long: 200
    RSI_length: 14
    MACD_fast: 12
    MACD_slow: 26
    MACD_signal: 9
    BB_length: 20
    BB_std: 2

# --- PORTAFOLIO ---
portafolio:
  capital_inicial: 10000.0
  apalancamiento: 1.0
  comision: 0.001
  slippage: 0.001

# --- ENTORNO DE ENTRENAMIENTO ---
entorno:
  window_size: 30
  max_drawdown_permitido: 0.2
  factor_aversion_riesgo: 2
  umbral_mantener_posicion: 0.05
  penalizacion_no_operar: 0.1
  episodios: 0                   # Se sobreescribe con CLI

# --- MODELO SAC ---
SACmodel:
  policy: "MultiInputPolicy"
  learning_rate: 3e-4
  buffer_size: 1000000
  learning_starts: 5000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  ent_coef: "auto_0.1"
  train_freq: [1, "step"]
  gradient_steps: 1
  verbose: 1
  seed: 42

# --- ARQUITECTURA DE RED ---
policy_kwargs:
  net_arch:
    pi: [256, 256]
    qf: [256, 256]
  log_std_init: -3.0
  n_critics: 2

# --- RUTAS DE SALIDA ---
output:
  datasets_dir: 'datasets'       # Carpeta base para datasets
  entrenamientos_dir: 'entrenamientos'  # Carpeta base para entrenamientos
  data_filename: 'data.csv'
  metadata_filename: 'metadata.yaml'
  scaler_filename: 'scaler.pkl'
