SACmodel:
  batch_size: 64
  buffer_size: 1000000
  ent_coef: auto_0.07345144250516616
  gamma: 0.9850715755806463
  gradient_steps: 1
  learning_rate: 0.0004283224849979167
  learning_starts: 4000
  policy: MultiInputPolicy
  seed: 42
  tau: 0.017352444523482287
  train_freq:
  - 1
  - step
  verbose: 1
data_downloader:
  limit: 1500
entorno:
  total_timesteps: 10000
  factor_aversion_riesgo: 1.6734292558460067
  max_drawdown_permitido: 0.23050916820666872
  normalizar_portfolio: True
  normalizar_recompensa: True
  penalizacion_no_operar: 0.0009107051853592882
  umbral_mantener_posicion: 0.05
  window_size: 100
  
  # ════════════════════════════════════════════════════════════
  # NUEVA FUNCIÓN DE RECOMPENSA MULTIFACTORIAL
  # ════════════════════════════════════════════════════════════
  
  # Normalización de recompensas
  factor_escala_recompensa: 116.71289028539161  # Escala retornos % a rango [-1, +1]
  
  # Pesos de componentes de recompensa (suman ~2.0 total)
  peso_retorno_base: 0.8891383444336317       # Cambio en equity
  peso_temporal:  0.30326977179374437          # Penalización/bonificación por tiempo
  peso_gestion: 0.09450732708883583            # Eficiencia en cierres
  peso_drawdown: 0.1304291873528854         # Protección contra ruina
  peso_inaccion: 0.05          # Anti-inacción
  
  # Parámetros de penalización temporal por pérdidas
  umbral_perdida_pct: 0.009906909686574074           # 0.5% pérdida mínima para activar
  factor_crecimiento_perdida: 0.05    # Penalización crece 5% por vela
  
  # Parámetros de bonificación por ganancias
  umbral_ganancia_pct: 0.004008242883188871         # 0.5% ganancia mínima para bonificar
  factor_moderacion_ganancia: 0.3     # Solo 30% de la ganancia como bonus
  factor_crecimiento_ganancia: 0.01   # Bonus crece 1% por vela
  
  # Parámetros de gestión eficiente (cierres)
  bonus_cierre_ganador: 0.02           # 2% bonus base por cerrar ganancia
  penalizacion_cierre_perdedor: -0.005 # -0.5% por cerrar pérdida (leve)
  
  # Parámetros de drawdown
  umbral_drawdown: 0.05               # 5% drawdown antes de penalizar
  factor_penalizacion_drawdown: 0.5   # Factor de penalización cuadrática
  
  # Parámetros de anti-inacción
  umbral_caida_equity: 0.002          # 0.2% caída de equity sin posición
  penalizacion_inaccion: -0.005       # -0.5% penalización por inacción
output:
  data_filename: data.csv
  datasets_dir: datasets
  entrenamientos_dir: entrenamientos
  metadata_filename: metadata.yaml
  scaler_filename: scaler.pkl
policy_kwargs:
  log_std_init: -2.035153637819397
  n_critics: 2
  net_arch:
    pi:
    - 512
    - 128
    - 128
    - 128
    qf:
    - 512
    - 128
    - 128
    - 128
portafolio:
  apalancamiento: 15.0
  capital_inicial: 10000.0
  comision: 0.001
  slippage: 0.001
preprocesamiento:
  indicadores:
    BB_length: 20
    BB_std: 2
    MACD_fast: 12
    MACD_signal: 9
    MACD_slow: 26
    RSI_length: 14
    SMA_long: 200
    SMA_short: 50
  interpol_method: linear
