SACmodel:
  batch_size: 256
  buffer_size: 1000000
  ent_coef: auto_0.1
  gamma: 0.99
  gradient_steps: 1
  learning_rate: 3e-4
  learning_starts: 5000
  policy: MultiInputPolicy
  seed: 42
  tau: 0.005
  train_freq:
  - 1
  - step
  verbose: 1
data_downloader:
  limit: 1500
entorno:
  episodios: 0
  factor_aversion_riesgo: 2
  max_drawdown_permitido: 0.2
  normalizar_portfolio: True
  normalizar_recompensa: True
  penalizacion_no_operar: 0.1
  umbral_mantener_posicion: 0.05
  window_size: 30
output:
  data_filename: data.csv
  datasets_dir: datasets
  entrenamientos_dir: entrenamientos
  metadata_filename: metadata.yaml
  scaler_filename: scaler.pkl
policy_kwargs:
  log_std_init: -3.0
  n_critics: 2
  net_arch:
    pi:
    - 256
    - 256
    qf:
    - 256
    - 256
portafolio:
  apalancamiento: 10.0
  capital_inicial: 10000.0
  comision: 0.001
  slippage: 0.001
preprocesamiento:
  indicadores:
    BB_length: 20
    BB_std: 2
    MACD_fast: 12
    MACD_signal: 9
    MACD_slow: 26
    RSI_length: 14
    SMA_long: 200
    SMA_short: 50
  interpol_method: linear
